FEAT - information about partitions are now logged
Nixtla/nixtla pull request #251
Opened 2024-03-14 19:02 UTC by marcopeix

The number of partitions is logged
We also log which partition is being treated

<img width="390" alt="Screenshot 2024-03-14 at 2 42 49 PM" src="https://github.com/Nixtla/nixtla/assets/19268689/8099c683-c8df-41c9-8630-59440a3f2b2b">

2024-04-08 02:16 UTC, AzulGarza approved these changes

2024-04-08 02:16 UTC, AzulGarza commented on nixtlats/nixtla_client.py
>          for uids_split in np.array_split(uids, num_partitions):
just a minor style comment, we could use  `enumerate`:

```python
splits = np.array_split(uids, num_partitions)
for split_index, uids_split in enumerate(splits, start=1):
     ...
```

non-blocking comment.

2024-04-08 02:19 UTC, AzulGarza requested changes
awesome @marcopeix! i left a minor comment. thank you! 🙌

2024-04-08 02:19 UTC, AzulGarza commented on nixtlats/nixtla_client.py
> +            main_logger.info(f"Partition {split_index} of {num_partitions}")
i just realized, if `len(uids) < num_partitions`, the logger can print incorrect partitions. i think it might be better to use:

```
splits = np.array_split(uids, num_partitions)
for ...:
     main_logger.info(f"Partition {split_index} of {len(splits)}")
```

2024-04-17 23:26 UTC, AzulGarza requested changes

2024-04-17 23:26 UTC, AzulGarza commented on nixtlats/nixtla_client.py
> +            split_index += 1
could you please remove this line? it is no longer needed since `enumerate` updates `split_index` in each iteration.  :)

2024-04-18 19:40 UTC, marcopeix commented on nixtlats/nixtla_client.py
> +            split_index += 1
Good catch! I removed it!

2024-04-19 14:26 UTC, marcopeix commented
Is this feature still relevant since partitions are now processed in parallel? The current output looks like this:
<img width="320" alt="Screenshot 2024-04-19 at 10 24 46 AM" src="https://github.com/Nixtla/nixtla/assets/19268689/803549c1-0854-4190-96cb-d043d85acd29">

2024-05-02 21:53 UTC, mergenthaler commented
@marcopeix, closing this for grooming. If you feel it should be kept open, please re-open and correct.

2024-05-02 21:53 UTC, closed without merging