Feat/token function
Nixtla/nixtla pull request #277
Opened 2024-04-02 06:21 UTC by MMenchero

## Description: 
Implemented new method for token information retrieval. 

## Changes: 
- Added new `request_df` method to TimeGPT class. 
- Added supporting methods and minor changes. 
- Supports main methods from TimeGPT class: `forecast`, `detect_anomalies`, and `cross_validation`. 

## Testing: 
See tests at the end of nb. 

## Notes: 
- Need to remove temporary fix to a minor issue when calling the `cross_validation` method.

2024-04-08 02:11 UTC, AzulGarza requested changes
hey @MMenchero! awesome progress! 🙌

i left a couple of comments. i think solving them will prevent the ci/cd from crashing. :)

2024-04-08 02:11 UTC, AzulGarza commented on nixtlats/nixtla_client.py
> +            created_at = time.strftime("%Y-%m-%d %H:%M:%S", local_time)
i think we can use `created_at = pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"))`, instead of importing `time`. probably this creates a compatibility issue with `tenacity` that explains the ci/cdm but i'm not completely sure.

2024-04-08 02:11 UTC, AzulGarza commented on nixtlats/nixtla_client.py
> +        self.nixtla_client_model = _NixtlaClientModel(
probably it might be better not to store `_NixtlaClientModel` to prevent the object from being heavy. We could use logic similar to `self.weights_x`. here, `_NixtlaClientModel`  stores `weights_x` and then `NixtlaClient` recovers that object. in the cases of the `requests_df`, `_NixtlaClientModel` might be storing that dataframe and then `NixtlaClient` appends new dataframes to the previously created one, something like:


```python
class NixtlaClient(_NixtlaClient):
     requests_df: pd.DataFrame = pd.DataFrame(columns=[...]) # add columns of request_df

     def _forecast(...):
          nixtla_client_model = _NixtlaClientModel(...)
          self.request_df = pd.concat([
              self.request_df, 
             nixtla_client_model.request_df], ignore_index=True,
          )
```

```

2024-04-29 20:06 UTC, MMenchero commented
This PR is ready for review @AzulGarza

2025-03-27 19:19 UTC, MMenchero commented
Closing this PR as this functionality is no longer needed and it hasn't been updated to the latest version of `nixtla`.

2025-03-27 19:20 UTC, MMenchero commented
Closing this PR as this functionality is no longer needed and it hasn't been updated to the latest version of `nixtla`.

2025-03-27 19:20 UTC, closed without merging