Hotfix/docs v030
Nixtla/nixtla pull request #282
Opened 2024-04-04 04:06 UTC by MMenchero

Updated the following docs with the new NixtlaClient class and methods: 
- FAQs 
- Setting Up Your Authentication API Key

2024-04-08 01:49 UTC, AzulGarza commented on nbs/docs/getting-started/1_getting_started_short.ipynb
>     "metadata": {},
<p>hiere is an error, i think just rerun it might solve it. s</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/282/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2024-04-08 01:49 UTC, AzulGarza commented on nbs/docs/getting-started/2_setting_up_your_authentication_token.ipynb
>       "name": "stderr",
<p>we should use <code>api_key</code> instead of <code>token</code>. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/282/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2024-04-08 01:49 UTC, AzulGarza commented on nbs/docs/misc/0_faqs.ipynb
>     "source": [
<p>the new ulr in docs.nixtla.io/docs will be <code>setting_up_your_authentication_api_key. </code> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/282/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2024-04-08 01:49 UTC, AzulGarza commented on nbs/docs/misc/0_faqs.ipynb
>     "source": [
<p>should we remove this callout warning?</p><p><code></code><code></p><p>::: {.callout-warning} &nbsp;Don't confuse the input, output, and finetune tokens with the TimeGPT token or API Key. The input, output, and finetune tokens are used to calculate your usage costs, while the TimeGPT token is used to authenticate your requests. &nbsp;::: </p><p></code><code></code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/282/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2024-04-08 01:49 UTC, AzulGarza commented on nbs/docs/misc/0_faqs.ipynb
>     "source": [
<p>This error occurs when your <code>TimeGPT</code> <em>api_key.</em></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/282/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='16'/>

2024-04-08 01:49 UTC, AzulGarza commented on nbs/docs/tutorials/11_loss_function_finetuning.ipynb
>     "cell_type": "code",
<p>thanks for adding this.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/282/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2024-04-08 01:49 UTC, AzulGarza commented on nbs/docs/tutorials/2_holidays.ipynb
>     "outputs": [],
<p>could we check what are the values of <code>weights_x</code> to see if we are returning zeros?   </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/282/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='14'/>

2024-04-08 01:49 UTC, AzulGarza commented on nbs/docs/tutorials/2_holidays.ipynb
>     "outputs": [],
<p>see previous comment</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/282/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='17'/>

2024-04-08 01:51 UTC, AzulGarza requested changes
awesome work @MMenchero @marcopeix! 🎉

i left a couple of comments. thank you!

2024-04-08 22:38 UTC, MMenchero commented on nbs/docs/misc/0_faqs.ipynb
>     "source": [
I'm actually surprised to see this callout because I know I deleted it since it's no longer necessary. I'll check if there was a problem with version control. Thanks for pointing it out!

2024-04-09 01:42 UTC, MMenchero commented on nbs/docs/tutorials/2_holidays.ipynb
>     "outputs": [],
<p>yes, the <code>weights_x</code> returns zeros. </p>

2024-04-09 01:42 UTC, MMenchero commented on nbs/docs/tutorials/2_holidays.ipynb
>     "outputs": [],
<p>here <code>weights_x</code> also returns zeros. </p>

2024-04-16 00:25 UTC, AzulGarza approved these changes

2024-04-16 00:25 UTC, merged