[FIX] Raise warning on missing X_df when df has exogenous
Nixtla/nixtla pull request #295
Opened 2024-04-18 19:38 UTC by elephaint

Adds a warning that exogenous features in `df` are ignored if `X_df` is not provided. 

Fix for #294 until we support historical exogenous variables in TimeGPT.

2024-04-19 04:34 UTC, AzulGarza requested changes

2024-04-19 04:34 UTC, AzulGarza commented on nixtlats/nixtla_client.py
> +
thanks @elephaint! since exogenous variables can be included for some methods, for example in `detect_anomalies` (see [this section of our docs](https://docs.nixtla.io/docs/anomaly_detection#exogenous-variables)), it might be better to include the warning in the [`preprocess_dataframe`](https://github.com/Nixtla/nixtla/blob/41298468045324fee30d510f39e6acd3f223deb7/nixtlats/nixtla_client.py#L430) function which handles this scenario (see for example, that the exogenous variables are used when `X_df is None and self.h is None`, the later case indicating the usage of `detect_anomalies`).  it might be a good idea to include the list of missing exogenous variables and a hint on how to solve the warning. 

also, please add a small test. thank you!🙌

2024-04-22 09:17 UTC, elephaint commented on nixtlats/nixtla_client.py
> +
Ok, changed the location and message, and added a test at the bottom of `nixtla_client.ipynb`

2024-05-06 20:31 UTC, AzulGarza commented on nixtla/nixtla_client.py
> +            missing_exogenous = df.drop(columns=y_cols).columns
it might be better to use `df.columns.drop(y_cols)` since `df.drop` creates a copy of the dataframe.

2024-05-06 21:26 UTC, elephaint commented on nixtla/nixtla_client.py
> +            missing_exogenous = df.drop(columns=y_cols).columns
Good point, fixed

2024-05-08 21:39 UTC, AzulGarza approved these changes

2024-05-09 07:50 UTC, merged