Electricity demand use case
Nixtla/nixtla pull request #321
Opened 2024-04-29 20:00 UTC by marcopeix

Compared TimeGPT and N-HiTS for a problem of electricity demand forecasting using [this dataset ](https://zenodo.org/records/4659727) from the Monash Repository, based on [this tutorial](https://cienciadedatos.net/documentos/py29-forecasting-electricity-power-demand-python.html) from SkForecast.

TimeGPT is more accurate and faster than N-HiTS.

Not sure how to handle the dataset, since I had to download it locally. Should I add it to the transfer-learning repo and use the GitHub raw link after?

2024-04-29 20:50 UTC, mergenthaler commented
>Not sure how to handle the dataset, since I had to download it locally. Should I add it to the transfer-learning repo and use the GitHub raw link after?
Yes, please.

2024-04-30 22:09 UTC, mergenthaler commented
@marcopeix, is this ready to be reviewed by Azul and merged?

2024-05-01 19:33 UTC, marcopeix commented
@AzulGarza , ready for review! 😄

2024-05-02 16:58 UTC, AzulGarza commented on nbs/docs/5_use_cases/3_electricity_demand.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #3.    input_df = df.groupby('unique_id').apply(lambda group: group.iloc[-1104:-96]).reset_index(drop=True)   # 1008 = 21 days (1008 *0.5h * 1 day/24h)
</pre><p>to prevent hardcoding <code>roup.iloc[-1104:-96]</code>,you could use <code>input_df = df.drop(test_df.index).reset_index(drop=True)</code>   </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/321/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='17'/>

2024-05-02 16:58 UTC, AzulGarza commented on nbs/docs/5_use_cases/3_electricity_demand.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #23.    df = read_tsf("data/australian_electricity_demand_dataset.tsf")
</pre><p>i think we need to change this dataframe to <code>df = read_tsf_from_url(url)</code>.also i think we can reuse <code>test_df</code> and <code>input_df</code> for both pipelines to prevent defining the same dataframes twice.     </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/321/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='28'/>

2024-05-02 16:59 UTC, AzulGarza requested changes
thanks @marcopeix! i left a couple of comments :)

2024-05-02 17:52 UTC, marcopeix commented on nbs/docs/5_use_cases/3_electricity_demand.ipynb
> +{
<p>I can't use the entire dataframe, because it is too large and it causes my kernel to crash locally. I need to select part of the data only. I'll reuse the same input and test dfs, but I'll have to slice.</p><p> </p>

2024-05-02 17:52 UTC, marcopeix commented on nbs/docs/5_use_cases/3_electricity_demand.ipynb
> +{
<p>Agreed, will fix this!</p>

2024-05-06 20:23 UTC, AzulGarza requested changes
thanks @marcopeix! 

i left a qq. also, could you please update [mint.json](https://github.com/Nixtla/nixtla/blob/main/nbs/mint.json) including the new notebooks? 
thanks!

2024-05-06 20:23 UTC, AzulGarza commented on .github/workflows/ci.yaml
> +        os: [ubuntu-latest, macos-13, windows-latest]
is there something in particular that breaks `macos-latest`? perhaps we can fix it in the notebooks, since the rest of the docu seems to work well with `macos-latest`.

2024-05-06 20:35 UTC, marcopeix commented on .github/workflows/ci.yaml
> +        os: [ubuntu-latest, macos-13, windows-latest]
On local, everything works fine, but in the CI, I encountered this error: 

`RuntimeError: MPS backend out of memory (MPS allocated: 0 bytes, other allocations: 0 bytes, max allowed: 7.93 GB). Tried to allocate 480.00 KB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).`

I reduced the batch size and val_batch_size, but that didn't fix the CI. José suggested I change it to `macos-latest`.

2024-05-06 23:37 UTC, AzulGarza approved these changes

2024-05-06 23:37 UTC, merged