Use case on missing values
Nixtla/nixtla pull request #326
Opened 2024-05-01 02:14 UTC by MMenchero

## Description

- Includes a new use case on how to deal with missing values in TimeGPT. 
- This is still a work in progress. See notes at the start of the nb.

2024-05-02 23:52 UTC, MMenchero commented
This is not compatible with the new structure of the docs, but this will be fixed once the new structure has been merged with main.

2024-05-03 18:54 UTC, mergenthaler commented on nbs/docs/5_use_cases/3_dealing_with_missing_values.ipynb
> +{
<p>Maybe you can add something like: <code>In demand forecastin use case it is often recommended to fill missing values with 0's.</code>  <span class="ql-cursor">﻿</span></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/326/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='25'/>

2024-05-06 03:22 UTC, MMenchero commented on nbs/docs/5_use_cases/3_dealing_with_missing_values.ipynb
> +{
There were some specific examples at the end, but I moved them to this section.

2024-05-06 03:23 UTC, MMenchero commented
This now includes the missing values tutorial and the glossary under the new docs structure.

2024-05-06 19:04 UTC, MMenchero commented
This is ready for review @AzulGarza @mergenthaler

2024-05-06 20:27 UTC, AzulGarza commented on nbs/docs/tutorials/19_missing_values.ipynb
> +{
<p>could we remove <code>engine="plotly"</code>? unfortunately, readme dot com doest not render interactive plots  😣</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/326/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2024-05-06 20:27 UTC, AzulGarza commented on nbs/docs/tutorials/19_missing_values.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    nixtla_client.plot(train_df_gaps, max_insample_length=800, engine='plotly')
</pre><p>same here.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/326/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='20'/>

2024-05-06 20:27 UTC, AzulGarza commented on nbs/docs/tutorials/19_missing_values.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    train_df_complete['y'] = train_df_complete['y'].interpolate(method='linear', limit_direction='both')
</pre><p>niceeeee</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/326/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='26'/>

2024-05-06 20:27 UTC, AzulGarza commented on nbs/docs/tutorials/19_missing_values.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    nixtla_client.plot(test_df, fcst, engine='plotly')
</pre><p>same comment here on plotly.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/326/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='31'/>

2024-05-06 20:28 UTC, AzulGarza requested changes

2024-05-06 20:28 UTC, AzulGarza commented on nbs/mint.json
cool

2024-05-06 22:49 UTC, MMenchero commented on nbs/docs/tutorials/19_missing_values.ipynb
> +{
sure, now I'm using `matplolib` and just mention to users `plotly` is another option. I also changed the Bitcoin Price Prediction tutorial since that one also used `plotly`.

2024-05-06 22:51 UTC, MMenchero commented on nbs/docs/tutorials/19_missing_values.ipynb
> +{
Well, it is what skforecast used 😅. We also mention in the tutorial that filling missing values is very context- dependent.

2024-05-06 23:36 UTC, AzulGarza approved these changes

2024-05-06 23:36 UTC, merged