[DOCS] Fix structure
Nixtla/nixtla pull request #329
Opened 2024-05-02 07:51 UTC by elephaint

- Minor structure fixes
- Consistent headings throughout docs
- List fixes

2024-05-02 22:41 UTC, AzulGarza requested changes
pretty cool, @elephaint! we just merged #312. could you please update this branch with main? i'm not sure those changes are compatible with the new structure. 🙈

2024-05-02 22:41 UTC, AzulGarza commented on action_files/readme_com/modify_markdown.py
> +    url = "https://dash.readme.com/api/v1/categories"
nice

2024-05-03 19:02 UTC, AzulGarza requested changes
thanks @elephaint! i left a couple of comments. could we also update the [sidebar](https://github.com/Nixtla/nixtla/blob/main/nbs/sidebar.yml) to match the same structure? (for preventing weird behavior). thank you!

2024-05-03 19:09 UTC, elephaint commented on nbs/mint.json
> +            "docs/capabilities/11_irregular_timestamps.html"
Correct - made these changes. 

The `00_forecast` is a placeholder for the category mostly for readme.com, and it gives a bit of a weird look on Mintlify, that's why it's not included.

2024-05-03 19:10 UTC, elephaint commented on nbs/mint.json
> +            "docs/capabilities/04_confidence_levels.html"
Good point, fixed

2024-05-03 19:12 UTC, elephaint commented on nbs/mint.json
> +            "docs/tutorials/05_multiple_series.html"
A bit same as for the first comment - in Mintlify, we can have explicit subcategories without a page belonging to it. Including that page will result in showing both the page and (separately) the subcategory, which looks a bit weird. That's why I only include them for readme.com, where we need them because readme.com doesn't support subcategories, only pages can be children of other pages.

2024-05-03 19:19 UTC, AzulGarza approved these changes

2024-05-03 19:20 UTC, merged