[DOC] - Reduce code blocks in capabilties
Nixtla/nixtla pull request #339
Opened 2024-05-06 20:32 UTC by marcopeix

Less code blocks in capabilities notebooks
Includes links to more detailed tutorials in the docu.

Number of code blocks cannot be reduced further because the CI blocks code cells with imports and code within the same cell.

2024-05-08 21:50 UTC, AzulGarza commented on nbs/docs/capabilities/anomaly-detection/01_quickstart.ipynb
>     "cell_type": "markdown",
<p>let's make sure all the nbs have similar headers, to maintain the same across nbs, eg</p><p>nbs/docs/capabilities/anomaly-detection/04_confidence_levels.ipynb does not have the initial text as header.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/339/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2024-05-08 21:50 UTC, AzulGarza commented on nbs/docs/capabilities/anomaly-detection/03_anomaly_detection_date_features.ipynb
>     "cell_type": "markdown",
<p>small typo: set instead of st.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/339/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2024-05-08 21:50 UTC, AzulGarza commented on nbs/docs/capabilities/anomaly-detection/04_confidence_levels.ipynb
>     "cell_type": "markdown",
<p>this should be a header?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/339/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2024-05-08 21:50 UTC, AzulGarza commented on nbs/docs/capabilities/forecast/08_custom_loss_function.ipynb
>     "cell_type": "markdown",
<p>first line as header.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/339/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2024-05-08 21:50 UTC, AzulGarza commented on nbs/docs/tutorials/20_anomaly_detection.ipynb
> +{
<p>this should be in a separate pr since we are mixing the colab strategy in #349 </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/339/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2024-05-08 21:51 UTC, AzulGarza requested changes
small comments regarding typos

2024-05-09 12:50 UTC, marcopeix commented on nbs/docs/capabilities/anomaly-detection/01_quickstart.ipynb
>     "cell_type": "markdown",
<p>Hello Azul! I don't know why in reviewNB the little text blurb is shown as a header. In the code, you see that it's just simple markdown with no "#". So, right now, all notebooks are consistent, in the sense that we have the header in the first cell, then we have a little blurb as normal text in the second cell. Not sure why it appears like this here. I'll rerun everything. It should look like in nbs/docs/capabilities/anomaly-detection/04_confidence_levels.ipynb </p>

2024-05-09 12:52 UTC, marcopeix commented on nbs/docs/capabilities/anomaly-detection/04_confidence_levels.ipynb
>     "cell_type": "markdown",
<p>No, just a little blurb to guide the users. The idea was to remove headers so that I could combine code blocks together and have less code blocks to copy/paste, as Max suggested.</p>

2024-05-09 12:56 UTC, marcopeix commented on nbs/docs/tutorials/20_anomaly_detection.ipynb
> +{
<p>Done</p>

2024-05-09 13:05 UTC, marcopeix commented on nbs/docs/capabilities/anomaly-detection/03_anomaly_detection_date_features.ipynb
>     "cell_type": "markdown",
Fixed

2024-05-09 13:05 UTC, marcopeix commented on nbs/docs/capabilities/anomaly-detection/01_quickstart.ipynb
>     "cell_type": "markdown",
<p>Fixed now!</p>

2024-05-10 03:07 UTC, AzulGarza approved these changes

2024-05-10 03:07 UTC, merged