[FEAT] What if - pricing in retail scenario
Nixtla/nixtla pull request #340
Opened 2024-05-06 21:11 UTC by elephaint

Adds simple use case for evaluating different pricing scenarios when forecasting product demand for a set of products in retail.

2024-05-07 11:47 UTC, elephaint commented
> View / edit / reply to [this conversation](https://app.reviewnb.com/Nixtla/nixtla/pull/340/discussion/#comment-2096983015) on ReviewNB
> 
> _mergenthaler commented on 2024-05-06T21:49:22Z_ ----------------------------------------------------------------
> 
> Maybe we can include a brief motivation or intro section. Something like:
> 
> `"What if" scenarios in time series analysis are essential across various sectors for strategic insight and decision-making. In finance, they help investors anticipate market reactions to economic events, enabling proactive risk management. Supply chains utilize these analyses to prepare for demand shifts or supplier issues, enhancing operational resilience. Energy companies forecast the impact of demand fluctuations or equipment failures to optimize production and grid management. In healthcare, scenario analysis aids in resource allocation and patient care optimization by predicting potential changes in staff or patient volumes. Retailers leverage these scenarios to adjust to shifts in consumer behavior or economic conditions, ensuring inventory and marketing strategies remain aligned with market demands. By preparing for potential future conditions, organizations enhance their strategic flexibility and resilience. `

Ok - added a sentence.

2024-05-07 11:48 UTC, elephaint commented
<p>Added a sentence</p>

---

 <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/340/discussion/#comment-2096983015'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-05-07 11:55 UTC, elephaint commented
<p>Added a callout-tip</p>

---

 <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/340/discussion/#comment-2096983028'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-05-07 12:10 UTC, elephaint commented
<p>Added a call-out note for elasticity reference and on assumptions.</p>

---

 <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/340/discussion/#comment-2096983046'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-05-07 12:17 UTC, elephaint commented
<p>Added conclusion to the text above the plot</p>

---

 <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/340/discussion/#comment-2096983063'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-05-07 19:14 UTC, mergenthaler commented
Thanks for the changes @elephaint! This is ready for your review @AzulGarza.

2024-05-08 21:54 UTC, AzulGarza requested changes
thanks @elephaint! i'm so sorry about asking for this change, but could you remove the colab part and wait to merge all colab changes in #349.

2024-05-10 03:13 UTC, AzulGarza approved these changes

2024-05-10 06:56 UTC, merged