Fixed links in documentation
Nixtla/nixtla pull request #341
Opened 2024-05-07 04:57 UTC by MMenchero

## Description 

Fixes links in docs: 
- Links that point to Mintlify now point to readme.com 
- Updated urls of some links
- Some links had typos that made them invalid.

2024-05-07 07:05 UTC, MMenchero commented
This is ready for review @AzulGarza @mergenthaler

2024-05-08 04:00 UTC, MMenchero commented
Added tutorial on data requirements for Getting Started section.

2024-05-08 21:59 UTC, AzulGarza commented on nbs/docs/getting-started/4_data_requirements.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #2.    df.head()
</pre><p>i think it might be better to add a dataframe that actually have different time series. i would suggest using the one form the readme. :)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/341/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2024-05-08 21:59 UTC, AzulGarza commented on nbs/docs/tutorials/17_computing_at_scale_spark_distributed.ipynb
>     "cell_type": "markdown",
<p>cool</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/341/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2024-05-08 21:59 UTC, AzulGarza requested changes
requesting small changes.

2024-05-08 22:08 UTC, mergenthaler commented on nbs/docs/getting-started/4_data_requirements.ipynb
> +{
<p>Maybe add a header before so users can identify this as an important issue on the right nav. </p><p>Also, it would be good to mention the distributed capabilities of TimeGPT. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/341/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='10'/>

2024-05-08 22:46 UTC, mergenthaler commented
Thanks for the small hot fix 😆

2024-05-09 06:43 UTC, MMenchero commented on nbs/docs/getting-started/4_data_requirements.ipynb
> +{
Done.

2024-05-09 06:55 UTC, MMenchero commented on nbs/docs/getting-started/4_data_requirements.ipynb
> +{
<p>Added header and distributed capabilities. </p>

2024-05-09 06:56 UTC, MMenchero commented
<p>I'm sorry, this should have 2 PRs: one for the correct links and one for the data requirements. </p>

2024-05-10 03:11 UTC, AzulGarza commented on nbs/docs/getting-started/4_data_requirements.ipynb
> +{
<p>love this new version!</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/341/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2024-05-10 03:11 UTC, AzulGarza approved these changes

2024-05-10 19:43 UTC, AzulGarza approved these changes

2024-05-10 21:07 UTC, merged