FEAT: Add feature contributions as attribute and tutorial on how to use
Nixtla/nixtla pull request #448
Opened 2024-08-16 19:58 UTC by marcopeix

Adds the attribute `feature_contributions` to the client when exogenous features are used. 
Tutorial on how to access feature contributions and use `shap` to make different plots.

2024-08-19 17:22 UTC, jmoralez commented on nixtla/nixtla_client.py
> +        ):
The field will always be there, we just have to check if its none or not.
```suggestion
        if first_res["feature_contributions"] is None:
```

2024-08-19 17:25 UTC, jmoralez commented on nixtla/nixtla_client.py
> +        feature_contributions: Optional[list[list[float]]],
This syntax was introduced in python 3.9, while we still support 3.8 we have to use `typing.List`. Please also change the weights method signature to use that.
```suggestion
        feature_contributions: Optional[List[List[float]]],
```

2024-08-19 17:27 UTC, jmoralez commented on nixtla/nixtla_client.py
> +            )
These are already column-oriented, so we can just create a dict with the column names
```suggestion
            shap_df = type(out_df)(
                dict(zip(x_cols + ["base_value"], feature_contributions))
            )
```

2024-08-19 17:31 UTC, jmoralez commented on nixtla/nixtla_client.py
> +        out_df: pd.DataFrame,
```suggestion
        out_df: DataFrame,
```

2024-08-19 17:32 UTC, jmoralez commented on nixtla/nixtla_client.py
> +            self.feature_contributions = pd.concat([out_df, shap_df], axis=1)
```suggestion
            self.feature_contributions = ufp.horizontal_concat([out_df, shap_df])
```

2024-08-19 17:34 UTC, jmoralez commented on nixtla/types/forecast_output.py
> +    feature_contributions: typing.Optional[typing.List[typing.List[float]]] = None
This code is generated automatically
```suggestion
```

2024-08-19 17:49 UTC, cchallu commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<p>The <code>colab_badge</code> has the <code>01_exogenous_variables</code> tutorial.  </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2024-08-19 17:49 UTC, cchallu commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #2.    if not IN_COLAB:
</pre><p> </p><p>I believe you are specifing the <code>base_url</code> to run it locally, but this won't work to users, so we need to remove it.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2024-08-19 17:49 UTC, cchallu commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<p>To have a more focused tutorial on shap values, I suggest to filter the example to the <code>NP</code> market. We can provide details on the meaning of each exogenous variables and interpret the SHAP values.  </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='13'/>

2024-08-19 17:49 UTC, cchallu commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<p>We need  to explain what is the <code>base_value</code> (without disclosing sensitive information). </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2024-08-19 17:49 UTC, cchallu commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #4.    shap_columns = shap_df.columns.difference(['unique_id', 'ds', 'TimeGPT', 'base_value'])
</pre><p> </p><p>Nice plots! I suggest keeping this simpler. Intead of plotting all series with a for loop, only plot the one we will use for the tutorial.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='21'/>

2024-08-19 17:49 UTC, cchallu commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<p>Can we provide more details on what is showing? (for example, the F(x) shows the forecasts for the 24 hours, heatmap represents the contribution of each exogenous variable on each timestamp).</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='24'/>

2024-08-19 18:59 UTC, jmoralez requested changes

2024-08-19 18:59 UTC, jmoralez commented on nixtla/nixtla_client.py
> +        if isinstance(weights[0], List):
```suggestion
        if isinstance(weights[0], list):
```

2024-08-19 18:59 UTC, jmoralez commented on nixtla/nixtla_client.py
> +        weights: Optional[Union[List[float, List[List[float]]]]],
Sorry, I think this was already wrong.
```suggestion
        weights: Optional[Union[List[float], List[List[float]]]],
```

2024-08-19 20:59 UTC, jmoralez requested changes

2024-08-19 20:59 UTC, jmoralez commented on nixtla/nixtla_client.py
> +        self._maybe_assign_feature_contributions(
We may drop the id above, so this should go before that. Also this still needs to handle the case for the in sample shaps, currently we'd just drop them. I think we can have a separate attribute for those.

2024-08-20 19:34 UTC, marcopeix commented on nixtla/nixtla_client.py
> +        self._maybe_assign_feature_contributions(
I think it's better to have everything in a single attribute that corresponds to the forecast dataframe. I think the experience will be better for the user. I modified to function to assign the attribute depending on whether we have insample shap values or not.

2024-08-21 16:55 UTC, elephaint reviewed
LGTM, but as I worked on it myself I won't approve.

2024-08-21 19:02 UTC, jmoralez requested changes

2024-08-21 19:02 UTC, jmoralez commented on nixtla/nixtla_client.py
> +                self.feature_contributions = ufp.horizontal_concat([out_df, shap_df])
```suggestion
        shap_cols = x_cols + ["base_value"]
        shap_df = type(out_df)(dict(zip(shap_cols, feature_contributions)))
        if insample_feat_contributions is not None:
            insample_shap_df = type(out_df)(
                dict(zip(shap_cols, insample_feat_contributions))
            )
            shap_df = ufp.vertical_concat([insample_shap_df, shap_df])
        self.feature_contributions = ufp.horizontal_concat([out_df, shap_df])
```

2024-08-21 19:02 UTC, jmoralez commented on nixtla/nixtla_client.py
>              out = ufp.sort(out, by=[id_col, time_col])
we have to move this sort after the shaps are assigned, otherwise they'll be wrong. bonus points if you do this only if necessary, i.e. we only need to sort if add history was true

2024-08-21 20:32 UTC, jmoralez commented on nixtla/nixtla_client.py
> +
For consistency I think we should also sort the feature contributions, so maybe something like this:
```suggestion
        if add_history:
            sort_idxs = ufp.maybe_compute_sort_indices(out, id_col=id_col, time_col=time_col)
            assert sort_idxs is not None
            out = ufp.take_rows(out, sort_idxs)
            self.feature_contributions = ufp.take_rows(self.feature_contributions, sort_idxs)
```

2024-08-23 16:08 UTC, jmoralez commented on nixtla/nixtla_client.py
> +            )
sorry, I messed up the suggestion
```suggestion
            if sort_idxs is not None:  # this is None for a single serie
                out = ufp.take_rows(out, sort_idxs)
                if feature_contributions:
                    self.feature_contributions = ufp.take_rows(
                        self.feature_contributions, sort_idxs
                    )
```

2024-08-26 15:04 UTC, jmoralez requested changes

2024-08-26 15:04 UTC, jmoralez commented on nixtla/nixtla_client.py
> +            "feature_contributions": feature_contributions,
Asking for contributions without providing `X` doesn't currently raise an error on the API, but it should
```suggestion
            "feature_contributions": feature_contributions and X is not None,
```

2024-08-26 15:04 UTC, jmoralez commented on nixtla/nixtla_client.py
> +                if feature_contributions:
```suggestion
                if hasattr(self, 'feature_contributions'):
```

2024-08-26 16:20 UTC, jmoralez commented
Thanks! Please add a test with num_partitions on the cell where the test for the contributions is. It can be something like the following:
```python
# this part already exists
fcst_hist_df = nixtla_client.forecast(df=df_date_features, h=h, X_df=future_df, add_history=True, feature_contributions=True)
shap_values_hist = nixtla_client.feature_contributions.copy()  # <- add the copy here
assert len(shap_values_hist) == len(fcst_hist_df)
np.testing.assert_allclose(fcst_hist_df["TimeGPT"].values, shap_values_hist.iloc[:, 3:].sum(axis=1).values)

# the following is new

# test num partitions
_ = nixtla_client.forecast(df=df_date_features, h=h, X_df=future_df, add_history=True, feature_contributions=True, num_partitions=2)
pd.testing.assert_frame_equal(nixtla_client.feature_contributions, shap_values_hist)
```

Also please add this on the forecast method:
```python
self.__dict__.pop('feature_contributions', None)
```
Just below the one for `weights_x`

2024-08-26 18:48 UTC, jmoralez approved these changes
Thanks!

Please don't merge this until we release v2, otherwise it'll show up in the docs and we'll get issues about it.

2024-08-29 03:23 UTC, mergenthaler commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<p>For SEO and Search Engines it might be Better to use copy like: <code>SHAP values for TimeGPT and TimeGEN</code>  <span class="ql-cursor">﻿</span></p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='4'/>

2024-08-29 03:23 UTC, mergenthaler commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<p>Maybe add something like: </p><p> </p>

<pre class="ql-syntax" spellcheck="false">SHAP can be installed from either&nbsp;PyPI&nbsp;or&nbsp;conda-forge:
</pre><p> </p>

<pre class="ql-syntax" spellcheck="false">
pip install shap

or

conda install -c conda-forge shap

for the official documentation visit: shap.readthedocs.io
</pre>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2024-08-29 03:23 UTC, mergenthaler commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<p>To make our AI models more accessible and helpful to users less familiar with time series literature, we could reframe this  as follows:</p><p>---</p><p>In this example on SHAP values, we will use exogenous variables (also known as covariates) to improve the accuracy of electricity market forecasts. We'll work with a well-known dataset called <code>EPF</code> , which is publicly accessible [<a href="https://github.com/jeslago/epftoolbox" target="_blank">here</a>]. This dataset includes data from five different electricity markets, each with unique price dynamics, such as varying frequencies and occurrences of negative prices, zeros, and price spikes. Since electricity prices are influenced by exogenous factors, each dataset also contains two additional time series: day-ahead forecasts of two significant exogenous factors specific to each market.</p><p> </p><p>For simplicity, we will focus on the Nord Pool electricity market (<code>NP</code> ), which corresponds to the Nordic countries' exchange. This dataset includes hourly prices (<code>y</code> ), day-ahead forecasts of load (<code>Exogenous 1</code> ), and wind generation (<code>Exogenous 2</code> ). It also includes one-hot encoding to indicate whether a specific date is a specific day of the week.  Eg.: Monday (<code>day_0 = 1</code> ), a Tuesday (<code>day_1 = 1</code> ), and so on.</p><p> </p><p>If your data depends on exogenous factors or covariates such as prices, discounts, special holidays, weather, etc., you can follow a similar structure.</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2024-08-29 03:23 UTC, mergenthaler commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<p>This seems to be a common problem that people encounter. I would suggest adding something like:</p><p> </p><p>"If your forecast depends on other variables, it is important to ensure that those variables are available at the time of forecasting. For example, if we know that the demand for a specific product depends on its price, you need to have the future prices available at the time of forecasting. If those prices are not available, you can always use TimeGPT to forecast them. [INCLUDE REF TO YOUR GREAT WORK ON HIST EXG]"</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2024-08-29 03:23 UTC, mergenthaler commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<p>Maybe something like:</p><p> </p><p>"Now that we have made predictions using exogenous features, we can then extract the SHAP values to _understand their relevance_ using the <code>feature_contributions</code> attribute of the client. This returns a DataFrame containing the SHAP values and base values for each series, at each step in the horizon."</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2024-08-29 03:23 UTC, mergenthaler commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<p>Maybe include some interpreation on why <code>day_0</code> is so relevant. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='24'/>

2024-09-03 19:26 UTC, merged

2024-09-24 03:05 UTC, zoeouyang2543 commented on nbs/docs/tutorials/21_shap_values.ipynb
> +{
<p>i met :TypeError: NixtlaClient.forecast() got an unexpected keyword argument 'feature_contributions'</p><p>the version of nixtla is 0.6.0</p>