[DOCS] Add API call count FAQ
Nixtla/nixtla pull request #449
Opened 2024-08-19 18:15 UTC by marcopeix

Add a section if FAQ to describe what counts as an API call. 

Covers situations with cross-validation, `num_partitions`, and forecast.

2024-08-20 19:32 UTC, elephaint requested changes
Nice work! See comments

2024-08-20 19:32 UTC, elephaint commented on nbs/docs/getting-started/5_faq.ipynb
> +    "An API call is a request made to TimeGPT to perform some an action like forecasting or detecting anomalies.\n",
Typo in this sentence, `to perform an action`

2024-08-20 19:32 UTC, elephaint commented on nbs/docs/getting-started/5_faq.ipynb
> +    "If we perform [cross-validation](https://docs.nixtla.io/docs/tutorials-cross_validation) using five windows, then it counts as 5 API calls, since the model must perform the forecast action twice
This confuses me - first we state five windows == five calls, then we talk about the forecasting action being performed twice (once per window)? 

I don't really get it?

2024-08-22 07:21 UTC, MMenchero commented on nbs/docs/getting-started/5_faq.ipynb
> +    "If we perform [cross-validation](https://docs.nixtla.io/docs/tutorials-cross_validation) using five windows, then it counts as 5 API calls, since the model must perform the forecast action twice
I would also remove the link to the computing at scale tutorials or put it at the end because those tutorials are about how to use `TimeGPT` with very specific frameworks and not really what `num_partitions` is about.

2024-08-26 14:27 UTC, marcopeix commented on nbs/docs/getting-started/5_faq.ipynb
> +    "If we perform [cross-validation](https://docs.nixtla.io/docs/tutorials-cross_validation) using five windows, then it counts as 5 API calls, since the model must perform the forecast action twice
Looks like on that day, 2 and 5 were the same for me! I fixed the typos and the confusion. I agree with removing the link to distirbuted computing.

2024-08-28 08:22 UTC, elephaint requested changes
I think we should mention the dataset size limit before we partition, so that users have a rough idea on how large they can go before they need to partition.

2024-08-28 08:22 UTC, elephaint commented on nbs/docs/getting-started/5_faq.ipynb
> +    "In some cases, the dataset can be too large and the API will return an error. Then, we must partition the data, using the `num_partitions` parameter. For example, if we set `num_partitions=2`, t
I think we should mention the dataset size limit here (200MB right?), so users know how big their data can be (roughly) before it needs to be partitioned. E.g.

```
If the API call requires to send more than 200MB of data, the API will return an error and will require you to use the `num_partitions` parameter in order to partition your request. Every partition will count as an API call, thus for 2 partitions there will be 2 API calls.
```

2024-08-28 14:52 UTC, marcopeix commented on nbs/docs/getting-started/5_faq.ipynb
> +    "In some cases, the dataset can be too large and the API will return an error. Then, we must partition the data, using the `num_partitions` parameter. For example, if we set `num_partitions=2`, t
Good point!

2024-08-30 17:10 UTC, tracykteal commented
Is it just 1 API call per forecast? Currently we need to make two requests to the API to generate forecasts. The first one gets the model's parameters to perform some preprocessing on the data, and the second one calls the actual path. 

So, when people make one forecast, they see 2 API requests in their dashboard. This could be a place where we explain that too.

2024-09-12 17:41 UTC, elephaint approved these changes
It needs a few reads to understand, but that's it's because complex how we made it (ie. the API call structure)

LGTM!

2024-09-13 15:11 UTC, merged