FEAT: Add finetune_depth parameter
Nixtla/nixtla pull request #471
Opened 2024-09-10 18:04 UTC by marcopeix

Add the `finetune_depth` parameter to control how many layers are finetuned.
Adjust tutorials and capabilities with new parameter.

2024-09-12 17:45 UTC, elephaint requested changes
Nice! Few comments, and I think we should include a test in `nixtla_client.ipynb`.

2024-09-12 17:45 UTC, elephaint commented on nixtla/nixtla_client.py
> +            Depth of finetuning, on a scale from 1 to 5. 1 means only the last layer is finetuned
We shouldn't talk about layers in the finetuning.

See the finetune_depth defintion in api-ltm

2024-09-12 17:45 UTC, elephaint commented on nixtla/nixtla_client.py
> +            Depth of finetuning, on a scale from 1 to 5. 1 means only the last layer is finetuned
See other comment, we shouldn't mention layers.

2024-09-12 17:45 UTC, elephaint commented on nbs/docs/capabilities/forecast/07_finetuning.ipynb
> +    "By default, only the last layer of the model is finetuned. We can finetune more layers using `finetune_depth` parameter. "
Not mention layers or any reference to architecture

2024-09-16 16:36 UTC, elephaint requested changes

2024-09-16 16:36 UTC, elephaint commented on nbs/docs/tutorials/06_finetuning.ipynb
> +    "`finetune_depth` takes values among `[1, 2, 3, 4, 5]`. By default, it is set to 1, which means that fine-tuning is shallow. When set to 5, the entire model is fine-tuned. Therefore, `finetune_de
We should not mention layers at all. Suggestion:

> `finetune_depth` takes values among `[1, 2, 3, 4, 5]`. By default, it is set to 1, which means mild finetuning, whereas a value of 5 means the maximum amount of finetuning. Increasing `finetune_depth` increases the time to generate predictions.`

2024-09-16 16:36 UTC, elephaint commented on nbs/src/nixtla_client.ipynb
> +    "            The depth of the finetuning. Uses a scale from 1 to 5, where 1 means little finetuning,\n",
Nice!

2024-09-16 18:08 UTC, marcopeix commented on nbs/docs/tutorials/06_finetuning.ipynb
> +    "`finetune_depth` takes values among `[1, 2, 3, 4, 5]`. By default, it is set to 1, which means that fine-tuning is shallow. When set to 5, the entire model is fine-tuned. Therefore, `finetune_de
It's harder than I though to not mention layers for this parameter! I kept "shallow" instead of "mild", I feel that "mild" confused me more, but I took the rest of the suggestion. Thanks for the help!

2024-09-24 09:57 UTC, elephaint approved these changes
LGTM, I removed last couple of mentions of layers.

2024-09-25 18:28 UTC, jmoralez requested changes
Please also add a test verifying that as the finetune depth increases the loss is lower in the `nbs/docs/tutorials/06_finetuning.ipynb` notebook.

2024-09-25 18:28 UTC, jmoralez commented on nixtla/nixtla_client.py
> +            and 5 means that the entire model is finetuned. By default, the value is set to 1.
```suggestion
            and 5 means that the entire model is finetuned.
```

2024-09-25 18:28 UTC, jmoralez commented on nixtla/nixtla_client.py
> +            and 5 means that the entire model is finetuned. By default, the value is set to 1.
```suggestion
            and 5 means that the entire model is finetuned.
```

2024-10-03 11:27 UTC, elephaint commented
> Please also add a test verifying that as the finetune depth increases the loss is lower in the `nbs/docs/tutorials/06_finetuning.ipynb` notebook.

Such a test doesn't always work; i.e. it's not always the case that finetuning improves the model. So I'm removing it again....

2024-10-03 16:00 UTC, jmoralez commented
What changed between now and 7bc1b5d1e554b1ad8fc7c420bcad1b87151b9048? That one has very different results ([nb link](https://github.com/Nixtla/nixtla/blob/7bc1b5d1e554b1ad8fc7c420bcad1b87151b9048/nbs/docs/tutorials/06_finetuning.ipynb)). This is supposed to be deterministic, isn't it? I'd expect to be able to reproduce the metrics from that commit every time, especially the monotonic part, right now 2 and 3 yield the same result which is highly suspicious.
![image](https://github.com/user-attachments/assets/d639cca6-4791-4586-88e0-af4b33434f8f)
![image](https://github.com/user-attachments/assets/10538dd0-2845-40da-8054-61b7f8ce0ec2)

2024-10-03 17:06 UTC, elephaint commented
> What changed between now and [7bc1b5d](https://github.com/Nixtla/nixtla/commit/7bc1b5d1e554b1ad8fc7c420bcad1b87151b9048)? That one has very different results ([nb link](https://github.com/Nixtla/nixtla/blob/7bc1b5d1e554b1ad8fc7c420bcad1b87151b9048/nbs/docs/tutorials/06_finetuning.ipynb)). This is supposed to be deterministic, isn't it? I'd expect to be able to reproduce the metrics from that commit every time, especially the monotonic part, right now 2 and 3 yield the same result which is highly suspicious. ![image](https://private-user-images.githubusercontent.com/8473587/373326158-d639cca6-4791-4586-88e0-af4b33434f8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NzQ2MjcsIm5iZiI6MTcyNzk3NDMyNywicGF0aCI6Ii84NDczNTg3LzM3MzMyNjE1OC1kNjM5Y2NhNi00NzkxLTQ1ODYtODhlMC1hZjRiMzM0MzRmOGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMTY1MjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjE1NTY3ZGNiZTQ4YzViODJjNzhkMDhiYTQyMjNiYWFlZjZlNDc5MWY2ODU2YWI2ZjJhYzhmNTc3MDc2ZGU3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SVPvlmRxbaF9pQdzjEfn3G0pOiBtjIjr5KGOIBoKBx4) ![image](https://private-user-images.githubusercontent.com/8473587/373326343-10538dd0-2845-40da-8054-61b7f8ce0ec2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NzQ2MjcsIm5iZiI6MTcyNzk3NDMyNywicGF0aCI6Ii84NDczNTg3LzM3MzMyNjM0My0xMDUzOGRkMC0yODQ1LTQwZGEtODA1NC02MWI3ZjhjZTBlYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMTY1MjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdjYmNhOGM4ZDY5YzM2NjU0N2M0NjkwNWEzYjg4YjY3YjJjNzU3YTQ4NWM2NzRmY2FiYmMzYmMzZjc3YzYzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FSHDBSMUnLmQ9cUIOLjPQFjHD08o_PCVZAQumPu759Q)

Nothing really changed, the issue is that it doesn't hold in general that:
- Finetune depth higher -> better performence
- Finetune steps more -> better performance

I tweaked the parameters so that the results are not good but monotonic (however as said before, finetuning isn't guaranteed to provide results that are strictly better when increasing the parameters)

2024-10-03 17:08 UTC, jmoralez commented
Thanks! So the test would pass now? It'd be great having `loss_depth1 > loss_depth2 > loss_depth3` to detect possible regressions or the parameter not being passed through correctly.

2024-10-03 17:42 UTC, elephaint commented
> Thanks! So the test would pass now? It'd be great having `loss_depth1 > loss_depth2 > loss_depth3` to detect possible regressions or the parameter not being passed through correctly.

No, because:
- Finetune depth higher does not lead to better performance in general
- Finetune steps higher does not lead to better performance in general
so we shouldn't market that view, either. And a test on that is useless too; if it fails, the results might still be better than before. 

I've updated the example to explain that also (so users see that increasing depth can also worsen performance, and it's a bit of trial and error).

The tutorial fails if the parameter isn't passed through correctly, so we're covered there anyways.

2024-10-03 17:48 UTC, jmoralez commented on nixtla/nixtla_client.py
> +            and 5 means that the entire model is finetuned. By default, the value is set to 1.
This is still here

2024-10-03 18:28 UTC, jmoralez approved these changes

2024-10-03 20:37 UTC, cchallu commented on nbs/docs/tutorials/06_finetuning.ipynb
>     "outputs": [],
<p>We need to rephrase this so that it is more clear for the user.</p><p> </p><p>Instead of "small amount of fine-tuning is applied", we should phrase it in terms of the number of parameters&nbsp;being fine-tuned. Something like: "<code>finetune_depth</code> ranges from 1 to 5 and controls the number of parameters of the model being fine-tuned. By default, it is set to 1, adjusting a small set of parameters, while a value of 5 fine-tunes the maximum number of parameters. Increasing <code>finetune_depth</code> will also extend the time needed to generate predictions."</p><p> </p><p>  </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/471/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2024-10-03 20:37 UTC, cchallu commented on nbs/docs/tutorials/06_finetuning.ipynb
>     "outputs": [],
<p>I like the conclusion! Some suggestions:</p><p> </p><ul><li>" but it can make it worse too" -&gt; " but it can make it worse too due to overfitting".</li><li>as a tip, mention that higher depth should work better for larger datasets. Relate to previous point saying that this is a 1 series dataset.</li></ul>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/471/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='24'/>

2024-10-03 20:40 UTC, cchallu submitted a review, later dismissed
see notebook

2024-10-10 09:58 UTC, elephaint approved these changes
LGTM, I only fixed some typos in the latest revision

2024-10-15 16:44 UTC, merged