breaking: add hist_exog argument to forecast
Nixtla/nixtla pull request #505
Opened 2024-10-23 21:55 UTC by jmoralez

2024-10-24 08:08 UTC, elephaint requested changes
Thanks @jmoralez! Two small comments from my side

2024-10-24 16:44 UTC, jmoralez commented on nbs/src/nixtla_client.ipynb
> +    "    hist_exog: Optional[List[str]],\n",
Agree on the change for consistency with neural.

2024-10-24 16:45 UTC, jmoralez commented on nbs/src/nixtla_client.ipynb
> +    "    ignored_exogs = [c for c in exogs if c not in {*hist_exog, *futr_exog}]\n",
I prefer the readability over 300 microseconds.

2024-10-24 16:47 UTC, jmoralez commented on nbs/src/nixtla_client.ipynb
> +    "    df = df[[id_col, time_col, target_col, *futr_exog, *hist_exog]]\n",
I don't like having the type in the name. I'm ok with the argument since we're stuck with that, but I don't see the point in naming things like `n_rows_int` or `fraction_float`.

2024-10-24 16:55 UTC, jmoralez commented on nbs/src/nixtla_client.ipynb
> +    "    ignored_exogs = [c for c in exogs if c not in {*hist_exog, *futr_exog}]\n",
It seems that the current version is slower because it builds the set on every iteration. I can extract that instead and that makes it faster than making everything sets, I'll push that change.

2024-10-29 17:21 UTC, elephaint approved these changes

2024-10-29 17:26 UTC, merged