FEAT: real-time anomaly detection
Nixtla/nixtla pull request #546
Opened 2024-11-26 21:14 UTC by marcopeix

Add new method for real-time anomaly detection

2024-12-10 16:02 UTC, marcopeix commented on nbs/docs/capabilities/realtime-anomaly-detection/01_quickstart.ipynb
> +{
<p>Can you read the CSV from a URL? Probably best to ask Cristian to upload the data to an S3 bucket and read from there.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='9'/>

2024-12-10 16:02 UTC, marcopeix commented on nbs/docs/capabilities/realtime-anomaly-detection/01_quickstart.ipynb
> +{
<p>What's the difference between flagged and detected?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='16'/>

2024-12-10 16:02 UTC, marcopeix commented on nbs/docs/capabilities/realtime-anomaly-detection/02_improve_detection_accuracy.ipynb
> +{
<p>Can you add another line change when running <code>detect_anomalies_realtime</code>?I just feel it's more readable if we do:</p><p> </p>

<pre class="ql-syntax" spellcheck="false">anomaly_df = nixtla_client.detect_anomalies_realtime(
    df,
    freq='D',
    ...
)
</pre>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='13'/>

2024-12-10 16:02 UTC, marcopeix commented on nbs/docs/capabilities/realtime-anomaly-detection/02_improve_detection_accuracy.ipynb
> +{
<p>I feel that if we say we are improving, then we should measure some metric. Is it possible to track f1-score, precision, recall for this dataset and see how the performance varies? Otherwise, maybe we could call it "Tuning the anomaly detection process"?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2024-12-10 16:02 UTC, marcopeix commented on nbs/docs/capabilities/realtime-anomaly-detection/03_univariate_vs_multivariate_anomaly_detection.ipynb
> +{
<p>Same as previous comment on adding a line change to make it more readable and avoid too much whitespace.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='14'/>

2024-12-10 16:02 UTC, marcopeix commented on nbs/docs/capabilities/realtime-anomaly-detection/03_univariate_vs_multivariate_anomaly_detection.ipynb
> +{
<p>Not sure if using horizontal bands makes it readable compared to using a marker in the plot to show flagged anomalies. Maybe we could use different markers for actual and detected anomalies? Something like a circle for actual and a square for detected?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2024-12-10 19:31 UTC, Yibei990826 commented on nbs/docs/capabilities/realtime-anomaly-detection/02_improve_detection_accuracy.ipynb
> +{
I’ve been checking the `F1` and `adjusted F1` (for anomaly detection tasks) scores to assess performance, but the improvement seems quite small. This might be due to two reasons: 1) the labels were manually added and may not be entirely accurate, and 2) the forecast improvements are subtle, so they don’t have a strong impact on detection.

You’re absolutely right! Let me take some time to think it through and see if we can find a way to demonstrate a clearer improvement in the metrics.

2024-12-11 19:49 UTC, marcopeix commented on nbs/docs/capabilities/realtime-anomaly-detection/01_quickstart.ipynb
> +{
<p>Before this cell, add callout for Azure AI URL</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='8'/>

2024-12-12 14:29 UTC, marcopeix commented on nbs/docs/capabilities/realtime-anomaly-detection/01_quickstart.ipynb
> +{
<p>"refer to the tutorial (coming soon)". Wdyt?</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2024-12-12 14:29 UTC, marcopeix commented on nbs/docs/capabilities/realtime-anomaly-detection/02_adjusting_detection_accuracy_process.ipynb
> +{
<p>For consistency, I would write "1. Conduct..." Putting a dot after the number. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2024-12-12 22:04 UTC, jmoralez requested changes
The endpoint is called online anomaly detection, so we should probably name the method the same, e.g. `detect_anomalies_online` or `online_anomaly_detection`

2024-12-12 22:04 UTC, jmoralez commented on nixtla/nixtla_client.py
> +        schema.append("anomaly_score:double")
There can also be intervals, right?

2024-12-13 15:40 UTC, marcopeix commented on nixtla/nixtla_client.py
> +_Threshold_Method = Literal["univariate", "multivariate"]
Also changed `_Finetune_Depth` to `_FinetuneDepth` for consistency

2024-12-13 16:04 UTC, marcopeix commented on nixtla/nixtla_client.py
> +        schema.append("anomaly_score:double")
Isn't that taken care of by the if statement on line 2474 `if level is not None:`?

2024-12-13 17:07 UTC, jmoralez commented on nixtla/nixtla_client.py
> +        schema.append("anomaly_score:double")
ah, you're right. thanks

2024-12-13 19:40 UTC, marcopeix commented on nixtla/nixtla_client.py
> +        validate_api_key: bool = False,
It's a required argument to the `_run_validations` function. Could we keep for now and do that refactor in another PR?

2024-12-17 22:33 UTC, jmoralez approved these changes
Nice! Just some minor comments, apart from that the implementation looks ok, I didn't look at the docs.

2024-12-20 02:10 UTC, cchallu commented on nbs/docs/capabilities/historical-anomaly-detection/02_anomaly_exogenous.ipynb
> +{
<p>Dont we need to change the path to historical-anomaly-detection here as well? And in all other notebooks.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2024-12-20 02:10 UTC, cchallu commented on nbs/docs/capabilities/online-anomaly-detection/00_online_anomaly_detection.ipynb
> +{
<p>Change to "Online (Real-time ) Anomaly Detection"</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2024-12-20 02:10 UTC, cchallu commented on nbs/docs/capabilities/online-anomaly-detection/00_online_anomaly_detection.ipynb
> +{
<p>Change steps to timestamps in first sentence</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2024-12-20 02:10 UTC, cchallu commented on nbs/docs/capabilities/online-anomaly-detection/01_quickstart.ipynb
> +{
<p>"Online (Real-time) .... "</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='4'/>

2024-12-20 02:10 UTC, cchallu commented on nbs/docs/capabilities/online-anomaly-detection/01_quickstart.ipynb
> +{
<ul><li>Change sentece "Therefore,..." to "You can tune all the same parameters from the forecast method to improve the performance."</li><li>Remove "indicates" in parenthesis on first paragraph</li><li>We are not using confidence levels (as in conformal prediction) to set thresholds. We should change the description of <code>level</code> to "Percentile of scores distribution at which the threshold is set, controlling how strictly anomalies are flagged. Default at 99%." </li></ul>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='14'/>

2024-12-20 02:10 UTC, cchallu commented on nbs/docs/capabilities/online-anomaly-detection/03_univariate_vs_multivariate_anomaly_detection.ipynb
> +{
<p>Remove this and paragraph below, it is confusing.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Nixtla/nixtla/pull/546/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='22'/>

2024-12-20 16:12 UTC, marcopeix commented on nbs/docs/capabilities/historical-anomaly-detection/02_anomaly_exogenous.ipynb
> +{
<p>Yes, thanks for catching that!</p>

2025-01-08 18:49 UTC, merged