docs: cleanup
Nixtla/nixtla pull request #578
Opened 2024-12-19 23:16 UTC by ngupta23

1. Fixed local error when running `nbdev_docs`

![image](https://github.com/user-attachments/assets/e488dfb4-7a36-4664-9805-372f655263e9)

2. Support email was not linked to email client. Fixed now.

3. Whitespace cleanup.

2024-12-19 23:40 UTC, jmoralez requested changes

2024-12-19 23:40 UTC, jmoralez commented on settings.ini
> +dev_requirements = black datasetsforecast fire hierarchicalforecast jupyterlab nbdev neuralforecast numpy<2 plotly polars pre-commit pyreadr python-dotenv pyyaml setuptools<70 statsforecast tabulate
pydantic is already in the requirements, you just didn't reinstall the lib
```suggestion
dev_requirements = black datasetsforecast fire hierarchicalforecast jupyterlab nbdev neuralforecast numpy<2 plotly polars pre-commit pyreadr python-dotenv pyyaml setuptools<70 statsforecast tabulate
```

2024-12-19 23:57 UTC, ngupta23 commented on settings.ini
> +dev_requirements = black datasetsforecast fire hierarchicalforecast jupyterlab nbdev neuralforecast numpy<2 plotly polars pre-commit pyreadr python-dotenv pyyaml setuptools<70 statsforecast tabulate
hmm.. that's interesting, somehow it did not get installed when I ran `uv pip install -Ue .[dev,distributed]`

2024-12-20 00:02 UTC, jmoralez approved these changes

2024-12-20 00:42 UTC, merged